# Site settings
title: "Puppy love"
email: jacob@jacobtomlinson.co.uk
description: "My adorable puppy."
baseurl: ""
url: "#"
title_description: "The cutest puppy in the world."
title_image: "http://dogbreedfinders.com/wp-content/uploads/sites/10/2014/07/Cute-Small-Dog-Breeds-Ever.jpg"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: _jacobtomlinson
github_username:  ingabazinga
linkedin_link: http://ingabazinga.github.io
google_plus_link: http://ingabazinga.github.io
stackoverflow_link: http://ingabazinga.github.io

# Footer
footer_left: "Made with <i class=\"fa fa-heart\">puppy love</i>"
footer_right: "&lt;puppylove/&gt; on <a href=\"https://github.com/IngaBazinga/ingabazinga.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
